2024-07-19 00:09:02,605 ERROR: Exception on /terms [GET] [in C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py", line 183, in entities
    rendered = render_template(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\templates\mdb.html", line 119, in template
    {% if subtype == "terms" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2024-07-19 00:09:02,734 INFO: model: All, page: 1, format:  [in C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py:94]
2024-07-19 00:09:02,744 ERROR: Exception on /favicon.ico [GET] [in C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py", line 168, in entities
    ents_ = dispatch[entities]["get_list"]( None if model == 'All' else model)
            ~~~~~~~~^^^^^^^^^^
KeyError: 'favicon.ico'
2024-07-19 00:09:03,301 INFO: model: All, page: 1, format:  [in C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py:94]
2024-07-19 00:09:03,311 ERROR: Exception on /favicon.ico [GET] [in C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\AppData\Local\pypoetry\Cache\virtualenvs\bento-sts-TqxUMP0n-py3.11\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py", line 168, in entities
    ents_ = dispatch[entities]["get_list"]( None if model == 'All' else model)
            ~~~~~~~~^^^^^^^^^^
KeyError: 'favicon.ico'
2024-07-19 00:09:04,608 INFO: model: All, page: 1, format:  [in C:\Users\Pranjal\Documents\GitHub\bento-sts\python\src\bento_sts\main\routes.py:94]
